services:
  postgres:
    image: postgres:15
    container_name: financeflow_db
    environment:
      POSTGRES_USER: financeflow
      POSTGRES_PASSWORD: financeflow123
      POSTGRES_DB: financeflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - financeflow_net

  financeflow-api:
    build: .
    container_name: financeflow_api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: main
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/financeflow
      SPRING_DATASOURCE_USERNAME: financeflow
      SPRING_DATASOURCE_PASSWORD: financeflow123
      JWT_SECRET: mySuperSecretKeyFinanceFlow
      JWT_EXPIRATION: 86400000
    depends_on:
      - postgres
    networks:
      - financeflow_net

volumes:
  postgres_data:

networks:
  financeflow_net:
